# Case Study -- Blue Riband {#riband}

The modern cruise passenger, who sees the ship as a major destination in itself, seldom thinks of speed as an interesting criteria for rating ships.  However, this was not always so.  For over a century and a half there was a prize - called the Blue Riband - for speed in the North Atlantic crossing.
 
After steam conquered that dangerous ocean, the fastest steamer was awarded a mythical "blue ribbon."  The start may have been Liverpool or Queenstown, but the end was always New York's Sandy Hook, or later, Ambrose Lightship, a distance of 2,800 nautical miles.
 
The term was borrowed from horse racing and was not widely used until after 1910. Under the unwritten rules, the record is based on average speed rather than passage time because ships follow different routes. Traditionally, a ship is considered a "record breaker" if it wins the eastbound speed record, but is not credited with the Blue Riband unless it wins the more difficult westbound record against the Gulf Stream.

Resources:

[The Blue Ribbon or Riband (Hales Trophy)](https://www.bluebird-electric.net/the_blue_ribband.htm)