---
title: "Network Analysis in R"
author: "Robert Wiederstein"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#link-citations: yes
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: tutorials on analyzing networks in R.
---

# Preface {-}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

## Why Read this Book

Network analysis is a crucial strategy in understanding the direction and strength of connections between people, places and ideas. Visual representation of networks can speed the discovery process in working with data. It has a wide variety of applications and has been used to study social media like twitter, [@grandjeanSocialNetworkAnalysis2016], dispersion of knowledge among inventors, [@brenneckeFirmKnowledgeNetwork2017] and the transmission of disease [@emchIntegrationSpatialSocial2012] , to name just a few.

The imagination of researchers to adopt social network analysis to new paradigms have left academic veterans reluctant to define its terms narrowly.  [@easleyNetworksCrowdsMarkets2012]

## Purpose

The purpose of this book is to speed the conversion of a traditional dataframe to a network diagram with nodes and vertices. Some discusson of basic computations will be included, but formulas are omitted unless necessary for understanding.  Network analysis is challenging partially due to its reliance on unfamiliar data structures.

## Collection

What follows is admittedly not the most original or insightful work on networks.  It is an attempt to collect tutorials from disparate packages, software and websites in a single place. Attribution will, of course, be given where known.

## Prerequisites

A working knowledge of `R` is necessary including how to obtain and load packages, how to manipulate basic data structures like lists and dataframes and how to plot and save graphs in multiple formats. Methods and packages in the `tidyverse` are preferred where available and  `Rstudio` is the development environment of choice.

## Disclaimer

I have no education or background in statistics, informatics or network analysis.  Reliance upon any representation within this publication should occur, if at all,  only after verification from other reliable sources and in consultation with someone with a relevant background.

## Acknowledgements

There were a number of helpful tutorials that deserve explicit mention and public acclaim.  The authors' differing perspectives gave context on how best to learn network analysis with `igraph`.  They include:

- [Katherine Ognyanova, Network Analysis and Visualization with R and igraph](https://kateto.net/networks-r-igraph)

- [Jesse Sadler, Introduction to Network Analysis with R](https://www.jessesadler.com/post/network-analysis-with-r/)

- [David Schoch, Basic Network Analysis in R: using igraph and related packages](http://mr.schochastics.net/netAnaR.html)

- [Network Visualization Cookbook](https://rstudio-pubs-static.s3.amazonaws.com/341807_7b9d1a4e787146d492115f90ad75cd2d.html#aspect_ratio)




